backend:
  name: git-gateway
  branch: main

collections:
  - name: "test"
    label: "Test Collection"
    folder: "_posts"
    create: true
    fields:
      - { label: "Title", name: "title", widget: "string" }
